### ISSUE TITLE
Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [seehuhn/dieharder#2]
Dear Jochen,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by seehuhn** [comment]
Sorry, I don't use Windows, so can't generate Windows binaries.  Also, so purpose of this repository is to make compiling `dieharder` easier, and providing binaries would be a bit contrary to this.

**Comment by bartengine27** [comment]
@sergeevabc  you can use the Windows subsystem for Linux https://docs.microsoft.com/en-us/windows/wsl/install-win10 and install with 'apt-get install dieharder'

**Comment by sergeevabc** [comment]
@bartengine27, alas, I can’t
as Linux subsystem is available for Windows 10 only,
while 7 is and will remain my OS of choice for the foreseeable future.
